#!/bin/sh

. ./config

git clone https://github.com/kaitai-io/kaitai_struct_javascript_runtime "$JAVASCRIPT_RUNTIME_DIR"

NODEJS_VERSION=$(node --version)

# Mocha dropped NodeJS v4 support since v6.0, so we'll be specifically using older version
MOCHA_VERSION=
if echo "$NODEJS_VERSION" | grep '^v4'; then
	MOCHA_VERSION="@5.2.0"
fi

cd tests

# Make sure that "node_modules" are always created in one location and avoid traversing to higher-level directories
mkdir -p node_modules

npm install "mocha$MOCHA_VERSION" iconv-lite
cd ..
