#!/bin/sh

. ./config

git clone https://github.com/kaitai-io/kaitai_struct_java_runtime "$JAVA_RUNTIME_DIR"

# Java: poor man's maven implementation in 3 lines :)
mkdir -p "$HOME/.m2/repository/org/testng/testng/6.9.10" "$HOME/.m2/repository/com/beust/jcommander/1.48"
wget -O "$HOME/.m2/repository/org/testng/testng/6.9.10/testng-6.9.10.jar" https://jcenter.bintray.com/org/testng/testng/6.9.10/testng-6.9.10.jar
wget -O "$HOME/.m2/repository/com/beust/jcommander/1.48/jcommander-1.48.jar" https://jcenter.bintray.com/com/beust/jcommander/1.48/jcommander-1.48.jar
