#!/bin/sh

. ./config

nimble refresh
nimble install testify
nimble install kaitai_struct_nim_runtime

export CHOOSENIM_NO_ANALYTICS=1
curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
sh init.sh -y
