#!/bin/sh

cd /opt/
wget https://github.com/nim-lang/Nim/archive/v1.0.0.zip
unzip v1.0.0.zip
cd Nim-1.0.0
chmod +x build_all.sh
./build_all.sh

nimble install kaitai_struct_nim_runtime
nimble install testify
