#!/bin/sh

. ./config

git clone https://github.com/kaitai-io/kaitai_struct_lua_runtime "$LUA_RUNTIME_DIR"

# Preinstall hererocks, lua installer
pip install hererocks

# Install lua
hererocks lua_install -r^ -l5.3
export PATH=$PATH:$PWD/lua_install/bin

# Check available versions
lua -v
luarocks -v

# Install Lua prerequisites
luarocks install luaunit
