#!/bin/sh

. ./config

git clone --depth 1 https://github.com/kaitai-io/kaitai_struct_csharp_runtime "$CSHARP_RUNTIME_DIR"
git -C "$CSHARP_RUNTIME_DIR" rev-parse HEAD

mono --version || :
cd tests
./run-csharp --project
nuget restore spec/csharp/kaitai_struct_csharp_tests.sln
