#!/bin/sh

. ./config

git clone https://github.com/kaitai-io/kaitai_struct_python_runtime "$PYTHON_RUNTIME_DIR"

pip install enum34

# this package dropped support for Python 2.7 since 3.0.0, so we're using the latest compatible version
pip install "unittest-xml-reporting~=2.5.2"
