#!/bin/sh

. ./config

git clone https://github.com/kaitai-io/kaitai_struct_php_runtime "$PHP_RUNTIME_DIR"

# PHP: newer PHPUnit, as the one in the repos is very old
wget https://phar.phpunit.de/phpunit.phar
chmod +x phpunit.phar
sudo mv phpunit.phar $HOME/bin/phpunit
$HOME/bin/phpunit --version
phpunit --version
