#!/bin/sh

. ./config

git clone https://github.com/kaitai-io/kaitai_struct_csharp_runtime "$CSHARP_RUNTIME_DIR"

mono --version || :
cd tests
./run-csharp --project
nuget restore spec/csharp/kaitai_struct_csharp_tests.sln
