// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type BitsUnalignedB64Le struct {
	A bool
	B uint64
	C uint64
	_io *kaitai.Stream
	_root *BitsUnalignedB64Le
	_parent kaitai.Struct
}
func NewBitsUnalignedB64Le() *BitsUnalignedB64Le {
	return &BitsUnalignedB64Le{
	}
}

func (this BitsUnalignedB64Le) IO_() *kaitai.Stream {
	return this._io
}

func (this *BitsUnalignedB64Le) Read(io *kaitai.Stream, parent kaitai.Struct, root *BitsUnalignedB64Le) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.A = tmp1 != 0
	tmp2, err := this._io.ReadBitsIntLe(64)
	if err != nil {
		return err
	}
	this.B = tmp2
	tmp3, err := this._io.ReadBitsIntLe(7)
	if err != nil {
		return err
	}
	this.C = tmp3
	return err
}
