// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type BitsByteAligned struct {
	One uint64
	Byte1 uint8
	Two uint64
	Three bool
	Byte2 uint8
	Four uint64
	Byte3 []byte
	FullByte uint64
	Byte4 uint8
	_io *kaitai.Stream
	_root *BitsByteAligned
	_parent kaitai.Struct
}
func NewBitsByteAligned() *BitsByteAligned {
	return &BitsByteAligned{
	}
}

func (this BitsByteAligned) IO_() *kaitai.Stream {
	return this._io
}

func (this *BitsByteAligned) Read(io *kaitai.Stream, parent kaitai.Struct, root *BitsByteAligned) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBitsIntBe(6)
	if err != nil {
		return err
	}
	this.One = tmp1
	this._io.AlignToByte()
	tmp2, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Byte1 = tmp2
	tmp3, err := this._io.ReadBitsIntBe(3)
	if err != nil {
		return err
	}
	this.Two = tmp3
	tmp4, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.Three = tmp4 != 0
	this._io.AlignToByte()
	tmp5, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Byte2 = tmp5
	tmp6, err := this._io.ReadBitsIntBe(14)
	if err != nil {
		return err
	}
	this.Four = tmp6
	this._io.AlignToByte()
	tmp7, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp7 = tmp7
	this.Byte3 = tmp7
	tmp8, err := this._io.ReadBitsIntBe(8)
	if err != nil {
		return err
	}
	this.FullByte = tmp8
	this._io.AlignToByte()
	tmp9, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Byte4 = tmp9
	return err
}
