// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type BitsSignedShiftB64Le struct {
	A uint64
	B uint64
	_io *kaitai.Stream
	_root *BitsSignedShiftB64Le
	_parent kaitai.Struct
}
func NewBitsSignedShiftB64Le() *BitsSignedShiftB64Le {
	return &BitsSignedShiftB64Le{
	}
}

func (this BitsSignedShiftB64Le) IO_() *kaitai.Stream {
	return this._io
}

func (this *BitsSignedShiftB64Le) Read(io *kaitai.Stream, parent kaitai.Struct, root *BitsSignedShiftB64Le) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBitsIntLe(63)
	if err != nil {
		return err
	}
	this.A = tmp1
	tmp2, err := this._io.ReadBitsIntLe(9)
	if err != nil {
		return err
	}
	this.B = tmp2
	return err
}
