// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type BitsByteAlignedEofBe struct {
	Prebuf []byte
	Bits uint64
	_io *kaitai.Stream
	_root *BitsByteAlignedEofBe
	_parent kaitai.Struct
}
func NewBitsByteAlignedEofBe() *BitsByteAlignedEofBe {
	return &BitsByteAlignedEofBe{
	}
}

func (this BitsByteAlignedEofBe) IO_() *kaitai.Stream {
	return this._io
}

func (this *BitsByteAlignedEofBe) Read(io *kaitai.Stream, parent kaitai.Struct, root *BitsByteAlignedEofBe) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.Prebuf = tmp1
	tmp2, err := this._io.ReadBitsIntBe(31)
	if err != nil {
		return err
	}
	this.Bits = tmp2
	return err
}
