// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type BitsSignedResB32Be struct {
	A uint64
	_io *kaitai.Stream
	_root *BitsSignedResB32Be
	_parent kaitai.Struct
}
func NewBitsSignedResB32Be() *BitsSignedResB32Be {
	return &BitsSignedResB32Be{
	}
}

func (this BitsSignedResB32Be) IO_() *kaitai.Stream {
	return this._io
}

func (this *BitsSignedResB32Be) Read(io *kaitai.Stream, parent kaitai.Struct, root *BitsSignedResB32Be) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBitsIntBe(32)
	if err != nil {
		return err
	}
	this.A = tmp1
	return err
}
