// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type BytesPadTermRoundtrip struct {
	StrPad []byte
	StrTerm []byte
	StrTermAndPad []byte
	StrTermInclude []byte
	_io *kaitai.Stream
	_root *BytesPadTermRoundtrip
	_parent kaitai.Struct
}
func NewBytesPadTermRoundtrip() *BytesPadTermRoundtrip {
	return &BytesPadTermRoundtrip{
	}
}

func (this BytesPadTermRoundtrip) IO_() *kaitai.Stream {
	return this._io
}

func (this *BytesPadTermRoundtrip) Read(io *kaitai.Stream, parent kaitai.Struct, root *BytesPadTermRoundtrip) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(20))
	if err != nil {
		return err
	}
	tmp1 = kaitai.BytesStripRight(tmp1, 64)
	this.StrPad = tmp1
	tmp2, err := this._io.ReadBytes(int(20))
	if err != nil {
		return err
	}
	tmp2 = kaitai.BytesTerminate(kaitai.BytesStripRight(tmp2, 43), 64, false)
	this.StrTerm = tmp2
	tmp3, err := this._io.ReadBytes(int(20))
	if err != nil {
		return err
	}
	tmp3 = kaitai.BytesTerminate(kaitai.BytesStripRight(tmp3, 43), 64, false)
	this.StrTermAndPad = tmp3
	tmp4, err := this._io.ReadBytes(int(20))
	if err != nil {
		return err
	}
	tmp4 = kaitai.BytesTerminate(kaitai.BytesStripRight(tmp4, 46), 64, true)
	this.StrTermInclude = tmp4
	return err
}
