// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type CastToImported2 struct {
	HwParam kaitai.Struct
	_io *kaitai.Stream
	_root *CastToImported2
	_parent kaitai.Struct
	_f_hw bool
	hw *HelloWorld
}
func NewCastToImported2(hwParam kaitai.Struct) *CastToImported2 {
	return &CastToImported2{
		HwParam: hwParam,
	}
}

func (this CastToImported2) IO_() *kaitai.Stream {
	return this._io
}

func (this *CastToImported2) Read(io *kaitai.Stream, parent kaitai.Struct, root *CastToImported2) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}
func (this *CastToImported2) Hw() (v *HelloWorld, err error) {
	if (this._f_hw) {
		return this.hw, nil
	}
	this._f_hw = true
	this.hw = this.HwParam.(*HelloWorld)
	return this.hw, nil
}
