// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type CastToImported struct {
	HwParam kaitai.Struct
	_io *kaitai.Stream
	_root *CastToImported
	_parent kaitai.Struct
	_f_hwOne bool
	hwOne uint8
}
func NewCastToImported(hwParam kaitai.Struct) *CastToImported {
	return &CastToImported{
		HwParam: hwParam,
	}
}

func (this CastToImported) IO_() *kaitai.Stream {
	return this._io
}

func (this *CastToImported) Read(io *kaitai.Stream, parent kaitai.Struct, root *CastToImported) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}
func (this *CastToImported) HwOne() (v uint8, err error) {
	if (this._f_hwOne) {
		return this.hwOne, nil
	}
	this._f_hwOne = true
	this.hwOne = uint8(this.HwParam.(*HelloWorld).One)
	return this.hwOne, nil
}
