// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type CombineBytes struct {
	BytesTerm []byte
	BytesLimit []byte
	BytesEos []byte
	_io *kaitai.Stream
	_root *CombineBytes
	_parent kaitai.Struct
	_f_bytesCalc bool
	bytesCalc []byte
	_f_eosOrCalc bool
	eosOrCalc []byte
	_f_limitOrCalc bool
	limitOrCalc []byte
	_f_limitOrEos bool
	limitOrEos []byte
	_f_termOrCalc bool
	termOrCalc []byte
	_f_termOrEos bool
	termOrEos []byte
	_f_termOrLimit bool
	termOrLimit []byte
}
func NewCombineBytes() *CombineBytes {
	return &CombineBytes{
	}
}

func (this CombineBytes) IO_() *kaitai.Stream {
	return this._io
}

func (this *CombineBytes) Read(io *kaitai.Stream, parent kaitai.Struct, root *CombineBytes) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytesTerm(124, false, true, true)
	if err != nil {
		return err
	}
	this.BytesTerm = tmp1
	tmp2, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp2 = tmp2
	this.BytesLimit = tmp2
	tmp3, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp3 = tmp3
	this.BytesEos = tmp3
	return err
}
func (this *CombineBytes) BytesCalc() (v []byte, err error) {
	if (this._f_bytesCalc) {
		return this.bytesCalc, nil
	}
	this.bytesCalc = []byte([]uint8{82, 110, 68})
	this._f_bytesCalc = true
	return this.bytesCalc, nil
}
func (this *CombineBytes) EosOrCalc() (v []byte, err error) {
	if (this._f_eosOrCalc) {
		return this.eosOrCalc, nil
	}
	var tmp4 []byte;
	if (true) {
		tmp4 = this.BytesEos
	} else {
		tmp5, err := this.BytesCalc()
		if err != nil {
			return nil, err
		}
		tmp4 = tmp5
	}
	this.eosOrCalc = []byte(tmp4)
	this._f_eosOrCalc = true
	return this.eosOrCalc, nil
}
func (this *CombineBytes) LimitOrCalc() (v []byte, err error) {
	if (this._f_limitOrCalc) {
		return this.limitOrCalc, nil
	}
	var tmp6 []byte;
	if (false) {
		tmp6 = this.BytesLimit
	} else {
		tmp7, err := this.BytesCalc()
		if err != nil {
			return nil, err
		}
		tmp6 = tmp7
	}
	this.limitOrCalc = []byte(tmp6)
	this._f_limitOrCalc = true
	return this.limitOrCalc, nil
}
func (this *CombineBytes) LimitOrEos() (v []byte, err error) {
	if (this._f_limitOrEos) {
		return this.limitOrEos, nil
	}
	var tmp8 []byte;
	if (true) {
		tmp8 = this.BytesLimit
	} else {
		tmp8 = this.BytesEos
	}
	this.limitOrEos = []byte(tmp8)
	this._f_limitOrEos = true
	return this.limitOrEos, nil
}
func (this *CombineBytes) TermOrCalc() (v []byte, err error) {
	if (this._f_termOrCalc) {
		return this.termOrCalc, nil
	}
	var tmp9 []byte;
	if (true) {
		tmp9 = this.BytesTerm
	} else {
		tmp10, err := this.BytesCalc()
		if err != nil {
			return nil, err
		}
		tmp9 = tmp10
	}
	this.termOrCalc = []byte(tmp9)
	this._f_termOrCalc = true
	return this.termOrCalc, nil
}
func (this *CombineBytes) TermOrEos() (v []byte, err error) {
	if (this._f_termOrEos) {
		return this.termOrEos, nil
	}
	var tmp11 []byte;
	if (false) {
		tmp11 = this.BytesTerm
	} else {
		tmp11 = this.BytesEos
	}
	this.termOrEos = []byte(tmp11)
	this._f_termOrEos = true
	return this.termOrEos, nil
}
func (this *CombineBytes) TermOrLimit() (v []byte, err error) {
	if (this._f_termOrLimit) {
		return this.termOrLimit, nil
	}
	var tmp12 []byte;
	if (true) {
		tmp12 = this.BytesTerm
	} else {
		tmp12 = this.BytesLimit
	}
	this.termOrLimit = []byte(tmp12)
	this._f_termOrLimit = true
	return this.termOrLimit, nil
}
