// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type EnumImportSeq struct {
	Pet1 Enum0_Animal
	Pet2 EnumDeep_Container1_Container2_Animal
	_io *kaitai.Stream
	_root *EnumImportSeq
	_parent kaitai.Struct
}
func NewEnumImportSeq() *EnumImportSeq {
	return &EnumImportSeq{
	}
}

func (this EnumImportSeq) IO_() *kaitai.Stream {
	return this._io
}

func (this *EnumImportSeq) Read(io *kaitai.Stream, parent kaitai.Struct, root *EnumImportSeq) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Pet1 = Enum0_Animal(tmp1)
	tmp2, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Pet2 = EnumDeep_Container1_Container2_Animal(tmp2)
	return err
}
