// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type EofExceptionU4 struct {
	Prebuf []byte
	FailInt uint32
	_io *kaitai.Stream
	_root *EofExceptionU4
	_parent kaitai.Struct
}
func NewEofExceptionU4() *EofExceptionU4 {
	return &EofExceptionU4{
	}
}

func (this EofExceptionU4) IO_() *kaitai.Stream {
	return this._io
}

func (this *EofExceptionU4) Read(io *kaitai.Stream, parent kaitai.Struct, root *EofExceptionU4) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(9))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.Prebuf = tmp1
	tmp2, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.FailInt = uint32(tmp2)
	return err
}
