// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type EofExceptionBitsLe2 struct {
	PreBits uint64
	FailBits uint64
	_io *kaitai.Stream
	_root *EofExceptionBitsLe2
	_parent kaitai.Struct
}
func NewEofExceptionBitsLe2() *EofExceptionBitsLe2 {
	return &EofExceptionBitsLe2{
	}
}

func (this EofExceptionBitsLe2) IO_() *kaitai.Stream {
	return this._io
}

func (this *EofExceptionBitsLe2) Read(io *kaitai.Stream, parent kaitai.Struct, root *EofExceptionBitsLe2) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBitsIntLe(8)
	if err != nil {
		return err
	}
	this.PreBits = tmp1
	tmp2, err := this._io.ReadBitsIntLe(17)
	if err != nil {
		return err
	}
	this.FailBits = tmp2
	return err
}
