// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type EofExceptionBitsBe struct {
	PreBits uint64
	FailBits uint64
	_io *kaitai.Stream
	_root *EofExceptionBitsBe
	_parent kaitai.Struct
}
func NewEofExceptionBitsBe() *EofExceptionBitsBe {
	return &EofExceptionBitsBe{
	}
}

func (this EofExceptionBitsBe) IO_() *kaitai.Stream {
	return this._io
}

func (this *EofExceptionBitsBe) Read(io *kaitai.Stream, parent kaitai.Struct, root *EofExceptionBitsBe) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBitsIntBe(7)
	if err != nil {
		return err
	}
	this.PreBits = tmp1
	tmp2, err := this._io.ReadBitsIntBe(18)
	if err != nil {
		return err
	}
	this.FailBits = tmp2
	return err
}
