// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type EofExceptionSwitchUser struct {
	Code uint16
	Data kaitai.Struct
	_io *kaitai.Stream
	_root *EofExceptionSwitchUser
	_parent kaitai.Struct
}
func NewEofExceptionSwitchUser() *EofExceptionSwitchUser {
	return &EofExceptionSwitchUser{
	}
}

func (this EofExceptionSwitchUser) IO_() *kaitai.Stream {
	return this._io
}

func (this *EofExceptionSwitchUser) Read(io *kaitai.Stream, parent kaitai.Struct, root *EofExceptionSwitchUser) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Code = uint16(tmp1)
	switch (this.Code) {
	case 2:
		tmp2 := NewEofExceptionSwitchUser_Two()
		err = tmp2.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Data = tmp2
	case 511:
		tmp3 := NewEofExceptionSwitchUser_One()
		err = tmp3.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Data = tmp3
	}
	return err
}
type EofExceptionSwitchUser_One struct {
	Val int16
	_io *kaitai.Stream
	_root *EofExceptionSwitchUser
	_parent *EofExceptionSwitchUser
}
func NewEofExceptionSwitchUser_One() *EofExceptionSwitchUser_One {
	return &EofExceptionSwitchUser_One{
	}
}

func (this EofExceptionSwitchUser_One) IO_() *kaitai.Stream {
	return this._io
}

func (this *EofExceptionSwitchUser_One) Read(io *kaitai.Stream, parent *EofExceptionSwitchUser, root *EofExceptionSwitchUser) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp4, err := this._io.ReadS2le()
	if err != nil {
		return err
	}
	this.Val = int16(tmp4)
	return err
}
type EofExceptionSwitchUser_Two struct {
	Val uint16
	_io *kaitai.Stream
	_root *EofExceptionSwitchUser
	_parent *EofExceptionSwitchUser
}
func NewEofExceptionSwitchUser_Two() *EofExceptionSwitchUser_Two {
	return &EofExceptionSwitchUser_Two{
	}
}

func (this EofExceptionSwitchUser_Two) IO_() *kaitai.Stream {
	return this._io
}

func (this *EofExceptionSwitchUser_Two) Read(io *kaitai.Stream, parent *EofExceptionSwitchUser, root *EofExceptionSwitchUser) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp5, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Val = uint16(tmp5)
	return err
}
