// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type EofExceptionBitsBe2 struct {
	PreBits uint64
	FailBits uint64
	_io *kaitai.Stream
	_root *EofExceptionBitsBe2
	_parent kaitai.Struct
}
func NewEofExceptionBitsBe2() *EofExceptionBitsBe2 {
	return &EofExceptionBitsBe2{
	}
}

func (this EofExceptionBitsBe2) IO_() *kaitai.Stream {
	return this._io
}

func (this *EofExceptionBitsBe2) Read(io *kaitai.Stream, parent kaitai.Struct, root *EofExceptionBitsBe2) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBitsIntBe(8)
	if err != nil {
		return err
	}
	this.PreBits = tmp1
	tmp2, err := this._io.ReadBitsIntBe(17)
	if err != nil {
		return err
	}
	this.FailBits = tmp2
	return err
}
