// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"bytes"
)

type EosExceptionSized struct {
	Envelope *EosExceptionSized_Data
	_io *kaitai.Stream
	_root *EosExceptionSized
	_parent kaitai.Struct
	_raw_Envelope []byte
}
func NewEosExceptionSized() *EosExceptionSized {
	return &EosExceptionSized{
	}
}

func (this EosExceptionSized) IO_() *kaitai.Stream {
	return this._io
}

func (this *EosExceptionSized) Read(io *kaitai.Stream, parent kaitai.Struct, root *EosExceptionSized) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(6))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this._raw_Envelope = tmp1
	_io__raw_Envelope := kaitai.NewStream(bytes.NewReader(this._raw_Envelope))
	tmp2 := NewEosExceptionSized_Data()
	err = tmp2.Read(_io__raw_Envelope, this, this._root)
	if err != nil {
		return err
	}
	this.Envelope = tmp2
	return err
}
type EosExceptionSized_Data struct {
	Buf *EosExceptionSized_Foo
	_io *kaitai.Stream
	_root *EosExceptionSized
	_parent *EosExceptionSized
	_raw_Buf []byte
}
func NewEosExceptionSized_Data() *EosExceptionSized_Data {
	return &EosExceptionSized_Data{
	}
}

func (this EosExceptionSized_Data) IO_() *kaitai.Stream {
	return this._io
}

func (this *EosExceptionSized_Data) Read(io *kaitai.Stream, parent *EosExceptionSized, root *EosExceptionSized) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp3, err := this._io.ReadBytes(int(7))
	if err != nil {
		return err
	}
	tmp3 = tmp3
	this._raw_Buf = tmp3
	_io__raw_Buf := kaitai.NewStream(bytes.NewReader(this._raw_Buf))
	tmp4 := NewEosExceptionSized_Foo()
	err = tmp4.Read(_io__raw_Buf, this, this._root)
	if err != nil {
		return err
	}
	this.Buf = tmp4
	return err
}
type EosExceptionSized_Foo struct {
	_io *kaitai.Stream
	_root *EosExceptionSized
	_parent *EosExceptionSized_Data
}
func NewEosExceptionSized_Foo() *EosExceptionSized_Foo {
	return &EosExceptionSized_Foo{
	}
}

func (this EosExceptionSized_Foo) IO_() *kaitai.Stream {
	return this._io
}

func (this *EosExceptionSized_Foo) Read(io *kaitai.Stream, parent *EosExceptionSized_Data, root *EosExceptionSized) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}
