// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type ExprBytesOps struct {
	One []byte
	_io *kaitai.Stream
	_root *ExprBytesOps
	_parent interface{}
	_f_twoSize bool
	twoSize int
	_f_twoLast bool
	twoLast uint8
	_f_oneSize bool
	oneSize int
	_f_oneMid bool
	oneMid uint8
	_f_twoMid bool
	twoMid uint8
	_f_oneLast bool
	oneLast uint8
	_f_oneMin bool
	oneMin uint8
	_f_oneMax bool
	oneMax uint8
	_f_two bool
	two []byte
	_f_twoMax bool
	twoMax uint8
	_f_twoMin bool
	twoMin uint8
	_f_twoFirst bool
	twoFirst uint8
	_f_oneFirst bool
	oneFirst uint8
}
func NewExprBytesOps() *ExprBytesOps {
	return &ExprBytesOps{
	}
}

func (this *ExprBytesOps) Read(io *kaitai.Stream, parent interface{}, root *ExprBytesOps) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(3))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.One = tmp1
	return err
}
func (this *ExprBytesOps) TwoSize() (v int, err error) {
	if (this._f_twoSize) {
		return this.twoSize, nil
	}
	tmp2, err := this.Two()
	if err != nil {
		return 0, err
	}
	this.twoSize = int(len(tmp2))
	this._f_twoSize = true
	return this.twoSize, nil
}
func (this *ExprBytesOps) TwoLast() (v uint8, err error) {
	if (this._f_twoLast) {
		return this.twoLast, nil
	}
	tmp4, err := this.Two()
	if err != nil {
		return 0, err
	}
	tmp3 := tmp4
	this.twoLast = uint8(tmp3[len(tmp3) - 1])
	this._f_twoLast = true
	return this.twoLast, nil
}
func (this *ExprBytesOps) OneSize() (v int, err error) {
	if (this._f_oneSize) {
		return this.oneSize, nil
	}
	this.oneSize = int(len(this.One))
	this._f_oneSize = true
	return this.oneSize, nil
}
func (this *ExprBytesOps) OneMid() (v uint8, err error) {
	if (this._f_oneMid) {
		return this.oneMid, nil
	}
	this.oneMid = uint8(this.One[1])
	this._f_oneMid = true
	return this.oneMid, nil
}
func (this *ExprBytesOps) TwoMid() (v uint8, err error) {
	if (this._f_twoMid) {
		return this.twoMid, nil
	}
	tmp5, err := this.Two()
	if err != nil {
		return 0, err
	}
	this.twoMid = uint8(tmp5[1])
	this._f_twoMid = true
	return this.twoMid, nil
}
func (this *ExprBytesOps) OneLast() (v uint8, err error) {
	if (this._f_oneLast) {
		return this.oneLast, nil
	}
	tmp6 := this.One
	this.oneLast = uint8(tmp6[len(tmp6) - 1])
	this._f_oneLast = true
	return this.oneLast, nil
}
func (this *ExprBytesOps) OneMin() (v uint8, err error) {
	if (this._f_oneMin) {
		return this.oneMin, nil
	}
	tmp7 := this.One[0]
	for _, tmp8 := range this.One {
		if tmp7 > tmp8 {
			tmp7 = tmp8
		}
	}
	this.oneMin = uint8(tmp7)
	this._f_oneMin = true
	return this.oneMin, nil
}
func (this *ExprBytesOps) OneMax() (v uint8, err error) {
	if (this._f_oneMax) {
		return this.oneMax, nil
	}
	tmp9 := this.One[0]
	for _, tmp10 := range this.One {
		if tmp9 < tmp10 {
			tmp9 = tmp10
		}
	}
	this.oneMax = uint8(tmp9)
	this._f_oneMax = true
	return this.oneMax, nil
}
func (this *ExprBytesOps) Two() (v []byte, err error) {
	if (this._f_two) {
		return this.two, nil
	}
	this.two = []byte([]uint8{65, 255, 75})
	this._f_two = true
	return this.two, nil
}
func (this *ExprBytesOps) TwoMax() (v uint8, err error) {
	if (this._f_twoMax) {
		return this.twoMax, nil
	}
	tmp13, err := this.Two()
	if err != nil {
		return 0, err
	}
	tmp11 := tmp13[0]
	tmp14, err := this.Two()
	if err != nil {
		return 0, err
	}
	for _, tmp12 := range tmp14 {
		if tmp11 < tmp12 {
			tmp11 = tmp12
		}
	}
	this.twoMax = uint8(tmp11)
	this._f_twoMax = true
	return this.twoMax, nil
}
func (this *ExprBytesOps) TwoMin() (v uint8, err error) {
	if (this._f_twoMin) {
		return this.twoMin, nil
	}
	tmp17, err := this.Two()
	if err != nil {
		return 0, err
	}
	tmp15 := tmp17[0]
	tmp18, err := this.Two()
	if err != nil {
		return 0, err
	}
	for _, tmp16 := range tmp18 {
		if tmp15 > tmp16 {
			tmp15 = tmp16
		}
	}
	this.twoMin = uint8(tmp15)
	this._f_twoMin = true
	return this.twoMin, nil
}
func (this *ExprBytesOps) TwoFirst() (v uint8, err error) {
	if (this._f_twoFirst) {
		return this.twoFirst, nil
	}
	tmp19, err := this.Two()
	if err != nil {
		return 0, err
	}
	this.twoFirst = uint8(tmp19[0])
	this._f_twoFirst = true
	return this.twoFirst, nil
}
func (this *ExprBytesOps) OneFirst() (v uint8, err error) {
	if (this._f_oneFirst) {
		return this.oneFirst, nil
	}
	this.oneFirst = uint8(this.One[0])
	this._f_oneFirst = true
	return this.oneFirst, nil
}
