// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"strconv"
)

type ExprToITrailing struct {
	_io *kaitai.Stream
	_root *ExprToITrailing
	_parent kaitai.Struct
	_f_toIGarbage bool
	toIGarbage int
	_f_toIR10 bool
	toIR10 int
	_f_toIR16 bool
	toIR16 int
}
func NewExprToITrailing() *ExprToITrailing {
	return &ExprToITrailing{
	}
}

func (this ExprToITrailing) IO_() *kaitai.Stream {
	return this._io
}

func (this *ExprToITrailing) Read(io *kaitai.Stream, parent kaitai.Struct, root *ExprToITrailing) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}
func (this *ExprToITrailing) ToIGarbage() (v int, err error) {
	if (this._f_toIGarbage) {
		return this.toIGarbage, nil
	}
	this._f_toIGarbage = true
	tmp1, err := strconv.ParseInt("123_.^", 10, 0)
	if err != nil {
		return 0, err
	}
	this.toIGarbage = int(tmp1)
	return this.toIGarbage, nil
}
func (this *ExprToITrailing) ToIR10() (v int, err error) {
	if (this._f_toIR10) {
		return this.toIR10, nil
	}
	this._f_toIR10 = true
	tmp2, err := strconv.ParseInt("9173abc", 10, 0)
	if err != nil {
		return 0, err
	}
	this.toIR10 = int(tmp2)
	return this.toIR10, nil
}
func (this *ExprToITrailing) ToIR16() (v int, err error) {
	if (this._f_toIR16) {
		return this.toIR16, nil
	}
	this._f_toIR16 = true
	tmp3, err := strconv.ParseInt("9173abc", 16, 0)
	if err != nil {
		return 0, err
	}
	this.toIR16 = int(tmp3)
	return this.toIR16, nil
}
