// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type ImportsCastToImported2 struct {
	Hw *HelloWorld
	Two *CastToImported2
	_io *kaitai.Stream
	_root *ImportsCastToImported2
	_parent kaitai.Struct
}
func NewImportsCastToImported2() *ImportsCastToImported2 {
	return &ImportsCastToImported2{
	}
}

func (this ImportsCastToImported2) IO_() *kaitai.Stream {
	return this._io
}

func (this *ImportsCastToImported2) Read(io *kaitai.Stream, parent kaitai.Struct, root *ImportsCastToImported2) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewHelloWorld()
	err = tmp1.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.Hw = tmp1
	tmp2 := NewCastToImported2(this.Hw)
	err = tmp2.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.Two = tmp2
	return err
}
