// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type ImportsCircularB struct {
	Initial uint8
	BackRef *ImportsCircularA
	_io *kaitai.Stream
	_root *ImportsCircularB
	_parent kaitai.Struct
}
func NewImportsCircularB() *ImportsCircularB {
	return &ImportsCircularB{
	}
}

func (this ImportsCircularB) IO_() *kaitai.Stream {
	return this._io
}

func (this *ImportsCircularB) Read(io *kaitai.Stream, parent kaitai.Struct, root *ImportsCircularB) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Initial = tmp1
	if (this.Initial == 65) {
		tmp2 := NewImportsCircularA()
		err = tmp2.Read(this._io, nil, nil)
		if err != nil {
			return err
		}
		this.BackRef = tmp2
	}
	return err
}
