// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type ImportsAbs struct {
	Len *VlqBase128Le
	Body []byte
	_io *kaitai.Stream
	_root *ImportsAbs
	_parent kaitai.Struct
}
func NewImportsAbs() *ImportsAbs {
	return &ImportsAbs{
	}
}

func (this ImportsAbs) IO_() *kaitai.Stream {
	return this._io
}

func (this *ImportsAbs) Read(io *kaitai.Stream, parent kaitai.Struct, root *ImportsAbs) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewVlqBase128Le()
	err = tmp1.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.Len = tmp1
	tmp2, err := this.Len.Value()
	if err != nil {
		return err
	}
	tmp3, err := this._io.ReadBytes(int(tmp2))
	if err != nil {
		return err
	}
	tmp3 = tmp3
	this.Body = tmp3
	return err
}
