// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type ImportsParamsDefArrayUsertypeImported struct {
	Hws []*HelloWorld
	Two *ParamsDefArrayUsertypeImported
	_io *kaitai.Stream
	_root *ImportsParamsDefArrayUsertypeImported
	_parent kaitai.Struct
}
func NewImportsParamsDefArrayUsertypeImported() *ImportsParamsDefArrayUsertypeImported {
	return &ImportsParamsDefArrayUsertypeImported{
	}
}

func (this ImportsParamsDefArrayUsertypeImported) IO_() *kaitai.Stream {
	return this._io
}

func (this *ImportsParamsDefArrayUsertypeImported) Read(io *kaitai.Stream, parent kaitai.Struct, root *ImportsParamsDefArrayUsertypeImported) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0; i < int(2); i++ {
		_ = i
		tmp1 := NewHelloWorld()
		err = tmp1.Read(this._io, nil, nil)
		if err != nil {
			return err
		}
		this.Hws = append(this.Hws, tmp1)
	}
	tmp2 := NewParamsDefArrayUsertypeImported(this.Hws)
	err = tmp2.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.Two = tmp2
	return err
}
