// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type ImportsAbsRel struct {
	One uint8
	Two *ImportedAndRel
	_io *kaitai.Stream
	_root *ImportsAbsRel
	_parent interface{}
}
func NewImportsAbsRel() *ImportsAbsRel {
	return &ImportsAbsRel{
	}
}

func (this *ImportsAbsRel) Read(io *kaitai.Stream, parent interface{}, root *ImportsAbsRel) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.One = tmp1
	tmp2 := NewImportedAndRel()
	err = tmp2.Read(this._io, this, nil)
	if err != nil {
		return err
	}
	this.Two = tmp2
	return err
}
