// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type ImportsCircularA struct {
	Code uint8
	Two *ImportsCircularB
	_io *kaitai.Stream
	_root *ImportsCircularA
	_parent interface{}
}
func NewImportsCircularA() *ImportsCircularA {
	return &ImportsCircularA{
	}
}

func (this *ImportsCircularA) Read(io *kaitai.Stream, parent interface{}, root *ImportsCircularA) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Code = tmp1
	tmp2 := NewImportsCircularB()
	err = tmp2.Read(this._io, this, nil)
	if err != nil {
		return err
	}
	this.Two = tmp2
	return err
}
