// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"io"
)

type InstanceStdArray struct {
	Ofs uint32
	EntrySize uint32
	QtyEntries uint32
	_io *kaitai.Stream
	_root *InstanceStdArray
	_parent interface{}
	_f_entries bool
	entries [][]byte
}
func NewInstanceStdArray() *InstanceStdArray {
	return &InstanceStdArray{
	}
}

func (this *InstanceStdArray) Read(io *kaitai.Stream, parent interface{}, root *InstanceStdArray) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Ofs = uint32(tmp1)
	tmp2, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.EntrySize = uint32(tmp2)
	tmp3, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.QtyEntries = uint32(tmp3)
	return err
}
func (this *InstanceStdArray) Entries() (v [][]byte, err error) {
	if (this._f_entries) {
		return this.entries, nil
	}
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64(this.Ofs), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this.QtyEntries); i++ {
		_ = i
		tmp4, err := this._io.ReadBytes(int(this.EntrySize))
		if err != nil {
			return nil, err
		}
		tmp4 = tmp4
		this.entries = append(this.entries, tmp4)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	this._f_entries = true
	this._f_entries = true
	return this.entries, nil
}
