// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type MetaXref struct {
	_io *kaitai.Stream
	_root *MetaXref
	_parent interface{}
}
func NewMetaXref() *MetaXref {
	return &MetaXref{
	}
}

func (this *MetaXref) Read(io *kaitai.Stream, parent interface{}, root *MetaXref) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}
