// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type NavRootRecursive struct {
	Value uint8
	Next *NavRootRecursive
	_io *kaitai.Stream
	_root *NavRootRecursive
	_parent kaitai.Struct
	_f_rootValue bool
	rootValue uint8
}
func NewNavRootRecursive() *NavRootRecursive {
	return &NavRootRecursive{
	}
}

func (this NavRootRecursive) IO_() *kaitai.Stream {
	return this._io
}

func (this *NavRootRecursive) Read(io *kaitai.Stream, parent kaitai.Struct, root *NavRootRecursive) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Value = tmp1
	if (this.Value == 255) {
		tmp2 := NewNavRootRecursive()
		err = tmp2.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Next = tmp2
	}
	return err
}
func (this *NavRootRecursive) RootValue() (v uint8, err error) {
	if (this._f_rootValue) {
		return this.rootValue, nil
	}
	this._f_rootValue = true
	this.rootValue = uint8(this._root.Value)
	return this.rootValue, nil
}
