// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type ParamsDefEnumImported struct {
	Pet1Param Enum0_Animal
	Pet2Param EnumDeep_Container1_Container2_Animal
	_io *kaitai.Stream
	_root *ParamsDefEnumImported
	_parent kaitai.Struct
}
func NewParamsDefEnumImported(pet1Param Enum0_Animal, pet2Param EnumDeep_Container1_Container2_Animal) *ParamsDefEnumImported {
	return &ParamsDefEnumImported{
		Pet1Param: pet1Param,
		Pet2Param: pet2Param,
	}
}

func (this ParamsDefEnumImported) IO_() *kaitai.Stream {
	return this._io
}

func (this *ParamsDefEnumImported) Read(io *kaitai.Stream, parent kaitai.Struct, root *ParamsDefEnumImported) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}
