// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"bytes"
)

type ParamsPassArrayIo struct {
	First *ParamsPassArrayIo_Block
	One *ParamsPassArrayIo_ParamType
	_io *kaitai.Stream
	_root *ParamsPassArrayIo
	_parent kaitai.Struct
	_raw_First []byte
}
func NewParamsPassArrayIo() *ParamsPassArrayIo {
	return &ParamsPassArrayIo{
	}
}

func (this ParamsPassArrayIo) IO_() *kaitai.Stream {
	return this._io
}

func (this *ParamsPassArrayIo) Read(io *kaitai.Stream, parent kaitai.Struct, root *ParamsPassArrayIo) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this._raw_First = tmp1
	_io__raw_First := kaitai.NewStream(bytes.NewReader(this._raw_First))
	tmp2 := NewParamsPassArrayIo_Block()
	err = tmp2.Read(_io__raw_First, this, this._root)
	if err != nil {
		return err
	}
	this.First = tmp2
	tmp3 := NewParamsPassArrayIo_ParamType([]*kaitai.Stream{this.First._io, this._root._io})
	err = tmp3.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.One = tmp3
	return err
}
type ParamsPassArrayIo_Block struct {
	Foo uint8
	_io *kaitai.Stream
	_root *ParamsPassArrayIo
	_parent *ParamsPassArrayIo
}
func NewParamsPassArrayIo_Block() *ParamsPassArrayIo_Block {
	return &ParamsPassArrayIo_Block{
	}
}

func (this ParamsPassArrayIo_Block) IO_() *kaitai.Stream {
	return this._io
}

func (this *ParamsPassArrayIo_Block) Read(io *kaitai.Stream, parent *ParamsPassArrayIo, root *ParamsPassArrayIo) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp4, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Foo = tmp4
	return err
}
type ParamsPassArrayIo_ParamType struct {
	Buf []byte
	ArgStreams []*kaitai.Stream
	_io *kaitai.Stream
	_root *ParamsPassArrayIo
	_parent *ParamsPassArrayIo
}
func NewParamsPassArrayIo_ParamType(argStreams []*kaitai.Stream) *ParamsPassArrayIo_ParamType {
	return &ParamsPassArrayIo_ParamType{
		ArgStreams: argStreams,
	}
}

func (this ParamsPassArrayIo_ParamType) IO_() *kaitai.Stream {
	return this._io
}

func (this *ParamsPassArrayIo_ParamType) Read(io *kaitai.Stream, parent *ParamsPassArrayIo, root *ParamsPassArrayIo) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp5, err := this.ArgStreams[0].Size()
	if err != nil {
		return err
	}
	tmp6, err := this._io.ReadBytes(int(tmp5))
	if err != nil {
		return err
	}
	tmp6 = tmp6
	this.Buf = tmp6
	return err
}
