// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"bytes"
)

type ParamsPassIo struct {
	First *ParamsPassIo_Block
	One *ParamsPassIo_ParamType
	_io *kaitai.Stream
	_root *ParamsPassIo
	_parent kaitai.Struct
	_raw_First []byte
}
func NewParamsPassIo() *ParamsPassIo {
	return &ParamsPassIo{
	}
}

func (this ParamsPassIo) IO_() *kaitai.Stream {
	return this._io
}

func (this *ParamsPassIo) Read(io *kaitai.Stream, parent kaitai.Struct, root *ParamsPassIo) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this._raw_First = tmp1
	_io__raw_First := kaitai.NewStream(bytes.NewReader(this._raw_First))
	tmp2 := NewParamsPassIo_Block()
	err = tmp2.Read(_io__raw_First, this, this._root)
	if err != nil {
		return err
	}
	this.First = tmp2
	var tmp3 *kaitai.Stream;
	if (this.First.Foo == 255) {
		tmp3 = this.First._io
	} else {
		tmp3 = this._root._io
	}
	tmp4 := NewParamsPassIo_ParamType(tmp3)
	err = tmp4.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.One = tmp4
	return err
}
type ParamsPassIo_Block struct {
	Foo uint8
	_io *kaitai.Stream
	_root *ParamsPassIo
	_parent *ParamsPassIo
}
func NewParamsPassIo_Block() *ParamsPassIo_Block {
	return &ParamsPassIo_Block{
	}
}

func (this ParamsPassIo_Block) IO_() *kaitai.Stream {
	return this._io
}

func (this *ParamsPassIo_Block) Read(io *kaitai.Stream, parent *ParamsPassIo, root *ParamsPassIo) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp5, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Foo = tmp5
	return err
}
type ParamsPassIo_ParamType struct {
	Buf []byte
	ArgStream *kaitai.Stream
	_io *kaitai.Stream
	_root *ParamsPassIo
	_parent *ParamsPassIo
}
func NewParamsPassIo_ParamType(argStream *kaitai.Stream) *ParamsPassIo_ParamType {
	return &ParamsPassIo_ParamType{
		ArgStream: argStream,
	}
}

func (this ParamsPassIo_ParamType) IO_() *kaitai.Stream {
	return this._io
}

func (this *ParamsPassIo_ParamType) Read(io *kaitai.Stream, parent *ParamsPassIo, root *ParamsPassIo) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp6, err := this.ArgStream.Size()
	if err != nil {
		return err
	}
	tmp7, err := this._io.ReadBytes(int(tmp6))
	if err != nil {
		return err
	}
	tmp7 = tmp7
	this.Buf = tmp7
	return err
}
