// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type ParamsPassArrayStr struct {
	StrArray []string
	PassStrArray *ParamsPassArrayStr_WantsStrs
	PassStrArrayCalc *ParamsPassArrayStr_WantsStrs
	_io *kaitai.Stream
	_root *ParamsPassArrayStr
	_parent kaitai.Struct
	_f_strArrayCalc bool
	strArrayCalc []string
}
func NewParamsPassArrayStr() *ParamsPassArrayStr {
	return &ParamsPassArrayStr{
	}
}

func (this ParamsPassArrayStr) IO_() *kaitai.Stream {
	return this._io
}

func (this *ParamsPassArrayStr) Read(io *kaitai.Stream, parent kaitai.Struct, root *ParamsPassArrayStr) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0; i < int(3); i++ {
		_ = i
		tmp1, err := this._io.ReadBytes(int(2))
		if err != nil {
			return err
		}
		tmp1 = tmp1
		this.StrArray = append(this.StrArray, string(tmp1))
	}
	tmp2 := NewParamsPassArrayStr_WantsStrs(this.StrArray)
	err = tmp2.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.PassStrArray = tmp2
	tmp4, err := this.StrArrayCalc()
	if err != nil {
		return err
	}
	tmp3 := NewParamsPassArrayStr_WantsStrs(tmp4)
	err = tmp3.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.PassStrArrayCalc = tmp3
	return err
}
func (this *ParamsPassArrayStr) StrArrayCalc() (v []string, err error) {
	if (this._f_strArrayCalc) {
		return this.strArrayCalc, nil
	}
	this.strArrayCalc = []string([]string{"aB", "Cd"})
	this._f_strArrayCalc = true
	return this.strArrayCalc, nil
}
type ParamsPassArrayStr_WantsStrs struct {
	Strs []string
	_io *kaitai.Stream
	_root *ParamsPassArrayStr
	_parent *ParamsPassArrayStr
}
func NewParamsPassArrayStr_WantsStrs(strs []string) *ParamsPassArrayStr_WantsStrs {
	return &ParamsPassArrayStr_WantsStrs{
		Strs: strs,
	}
}

func (this ParamsPassArrayStr_WantsStrs) IO_() *kaitai.Stream {
	return this._io
}

func (this *ParamsPassArrayStr_WantsStrs) Read(io *kaitai.Stream, parent *ParamsPassArrayStr, root *ParamsPassArrayStr) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}
