// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type ProcessBytesPadTerm struct {
	StrPad []byte
	StrTerm []byte
	StrTermAndPad []byte
	StrTermInclude []byte
	_io *kaitai.Stream
	_root *ProcessBytesPadTerm
	_parent kaitai.Struct
	_raw_StrPad []byte
	_raw_StrTerm []byte
	_raw_StrTermAndPad []byte
	_raw_StrTermInclude []byte
}
func NewProcessBytesPadTerm() *ProcessBytesPadTerm {
	return &ProcessBytesPadTerm{
	}
}

func (this ProcessBytesPadTerm) IO_() *kaitai.Stream {
	return this._io
}

func (this *ProcessBytesPadTerm) Read(io *kaitai.Stream, parent kaitai.Struct, root *ProcessBytesPadTerm) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(20))
	if err != nil {
		return err
	}
	tmp1 = kaitai.BytesStripRight(tmp1, 64)
	this._raw_StrPad = tmp1
	this.StrPad = kaitai.ProcessXOR(this._raw_StrPad, []byte{21})
	tmp2, err := this._io.ReadBytes(int(20))
	if err != nil {
		return err
	}
	tmp2 = kaitai.BytesTerminate(tmp2, 64, false)
	this._raw_StrTerm = tmp2
	this.StrTerm = kaitai.ProcessXOR(this._raw_StrTerm, []byte{21})
	tmp3, err := this._io.ReadBytes(int(20))
	if err != nil {
		return err
	}
	tmp3 = kaitai.BytesTerminate(kaitai.BytesStripRight(tmp3, 43), 64, false)
	this._raw_StrTermAndPad = tmp3
	this.StrTermAndPad = kaitai.ProcessXOR(this._raw_StrTermAndPad, []byte{21})
	tmp4, err := this._io.ReadBytes(int(20))
	if err != nil {
		return err
	}
	tmp4 = kaitai.BytesTerminate(tmp4, 64, true)
	this._raw_StrTermInclude = tmp4
	this.StrTermInclude = kaitai.ProcessXOR(this._raw_StrTermInclude, []byte{21})
	return err
}
