// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type ProcessCustomNoArgs struct {
	Buf []byte
	_io *kaitai.Stream
	_root *ProcessCustomNoArgs
	_parent kaitai.Struct
	_raw_Buf []byte
}
func NewProcessCustomNoArgs() *ProcessCustomNoArgs {
	return &ProcessCustomNoArgs{
	}
}

func (this ProcessCustomNoArgs) IO_() *kaitai.Stream {
	return this._io
}

func (this *ProcessCustomNoArgs) Read(io *kaitai.Stream, parent kaitai.Struct, root *ProcessCustomNoArgs) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(5))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this._raw_Buf = tmp1
	this.Buf = this._raw_Buf
	return err
}
