// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type ProcessXor4Value struct {
	Key []byte
	Buf []byte
	_io *kaitai.Stream
	_root *ProcessXor4Value
	_parent kaitai.Struct
	_raw_Buf []byte
}
func NewProcessXor4Value() *ProcessXor4Value {
	return &ProcessXor4Value{
	}
}

func (this ProcessXor4Value) IO_() *kaitai.Stream {
	return this._io
}

func (this *ProcessXor4Value) Read(io *kaitai.Stream, parent kaitai.Struct, root *ProcessXor4Value) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.Key = tmp1
	tmp2, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp2 = tmp2
	this._raw_Buf = tmp2
	this.Buf = kaitai.ProcessXOR(this._raw_Buf, this.Key)
	return err
}
