// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type RepeatNBytes struct {
	Records [][]byte
	_io *kaitai.Stream
	_root *RepeatNBytes
	_parent kaitai.Struct
}
func NewRepeatNBytes() *RepeatNBytes {
	return &RepeatNBytes{
	}
}

func (this RepeatNBytes) IO_() *kaitai.Stream {
	return this._io
}

func (this *RepeatNBytes) Read(io *kaitai.Stream, parent kaitai.Struct, root *RepeatNBytes) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0; i < int(3); i++ {
		_ = i
		tmp1, err := this._io.ReadBytes(int(5))
		if err != nil {
			return err
		}
		tmp1 = tmp1
		this.Records = append(this.Records, tmp1)
	}
	return err
}
