// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type RepeatEosBitsB4 struct {
	Nibbles []uint64
	_io *kaitai.Stream
	_root *RepeatEosBitsB4
	_parent kaitai.Struct
}
func NewRepeatEosBitsB4() *RepeatEosBitsB4 {
	return &RepeatEosBitsB4{
	}
}

func (this RepeatEosBitsB4) IO_() *kaitai.Stream {
	return this._io
}

func (this *RepeatEosBitsB4) Read(io *kaitai.Stream, parent kaitai.Struct, root *RepeatEosBitsB4) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0;; i++ {
		tmp1, err := this._io.EOF()
		if err != nil {
			return err
		}
		if tmp1 {
			break
		}
		tmp2, err := this._io.ReadBitsIntBe(4)
		if err != nil {
			return err
		}
		this.Nibbles = append(this.Nibbles, tmp2)
	}
	return err
}
