// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type RepeatNBytesPadTerm struct {
	Records [][]byte
	_io *kaitai.Stream
	_root *RepeatNBytesPadTerm
	_parent kaitai.Struct
}
func NewRepeatNBytesPadTerm() *RepeatNBytesPadTerm {
	return &RepeatNBytesPadTerm{
	}
}

func (this RepeatNBytesPadTerm) IO_() *kaitai.Stream {
	return this._io
}

func (this *RepeatNBytesPadTerm) Read(io *kaitai.Stream, parent kaitai.Struct, root *RepeatNBytesPadTerm) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0; i < int(3); i++ {
		_ = i
		tmp1, err := this._io.ReadBytes(int(5))
		if err != nil {
			return err
		}
		tmp1 = kaitai.BytesTerminate(kaitai.BytesStripRight(tmp1, 170), 85, true)
		this.Records = append(this.Records, tmp1)
	}
	return err
}
