// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type RepeatEosBytesPad struct {
	Records [][]byte
	_io *kaitai.Stream
	_root *RepeatEosBytesPad
	_parent kaitai.Struct
}
func NewRepeatEosBytesPad() *RepeatEosBytesPad {
	return &RepeatEosBytesPad{
	}
}

func (this RepeatEosBytesPad) IO_() *kaitai.Stream {
	return this._io
}

func (this *RepeatEosBytesPad) Read(io *kaitai.Stream, parent kaitai.Struct, root *RepeatEosBytesPad) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0;; i++ {
		tmp1, err := this._io.EOF()
		if err != nil {
			return err
		}
		if tmp1 {
			break
		}
		tmp2, err := this._io.ReadBytes(int(5))
		if err != nil {
			return err
		}
		tmp2 = kaitai.BytesStripRight(tmp2, 170)
		this.Records = append(this.Records, tmp2)
	}
	return err
}
