// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type RepeatNStrzDouble struct {
	Qty uint32
	Lines1 []string
	Lines2 []string
	_io *kaitai.Stream
	_root *RepeatNStrzDouble
	_parent kaitai.Struct
}
func NewRepeatNStrzDouble() *RepeatNStrzDouble {
	return &RepeatNStrzDouble{
	}
}

func (this RepeatNStrzDouble) IO_() *kaitai.Stream {
	return this._io
}

func (this *RepeatNStrzDouble) Read(io *kaitai.Stream, parent kaitai.Struct, root *RepeatNStrzDouble) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Qty = uint32(tmp1)
	for i := 0; i < int(this.Qty / 2); i++ {
		_ = i
		tmp2, err := this._io.ReadBytesTerm(0, false, true, true)
		if err != nil {
			return err
		}
		this.Lines1 = append(this.Lines1, string(tmp2))
	}
	for i := 0; i < int(this.Qty / 2); i++ {
		_ = i
		tmp3, err := this._io.ReadBytesTerm(0, false, true, true)
		if err != nil {
			return err
		}
		this.Lines2 = append(this.Lines2, string(tmp3))
	}
	return err
}
