// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"bytes"
)

type RepeatUntilSized struct {
	Records []*RepeatUntilSized_Record
	_io *kaitai.Stream
	_root *RepeatUntilSized
	_parent kaitai.Struct
	_raw_Records [][]byte
}
func NewRepeatUntilSized() *RepeatUntilSized {
	return &RepeatUntilSized{
	}
}

func (this RepeatUntilSized) IO_() *kaitai.Stream {
	return this._io
}

func (this *RepeatUntilSized) Read(io *kaitai.Stream, parent kaitai.Struct, root *RepeatUntilSized) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 1;; i++ {
		tmp1, err := this._io.ReadBytes(int(5))
		if err != nil {
			return err
		}
		tmp1 = tmp1
		_buf := tmp1
		this._raw_Records = append(this._raw_Records, _buf)
		_io__raw_Records := kaitai.NewStream(bytes.NewReader(_buf))
		tmp2 := NewRepeatUntilSized_Record()
		err = tmp2.Read(_io__raw_Records, this, this._root)
		if err != nil {
			return err
		}
		_it := tmp2
		this.Records = append(this.Records, _it)
		if _it.Marker == 170 {
			break
		}
	}
	return err
}
type RepeatUntilSized_Record struct {
	Marker uint8
	Body uint32
	_io *kaitai.Stream
	_root *RepeatUntilSized
	_parent *RepeatUntilSized
}
func NewRepeatUntilSized_Record() *RepeatUntilSized_Record {
	return &RepeatUntilSized_Record{
	}
}

func (this RepeatUntilSized_Record) IO_() *kaitai.Stream {
	return this._io
}

func (this *RepeatUntilSized_Record) Read(io *kaitai.Stream, parent *RepeatUntilSized, root *RepeatUntilSized) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp3, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Marker = tmp3
	tmp4, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Body = uint32(tmp4)
	return err
}
