// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"bytes"
)

type StrEosPadTermEmpty struct {
	StrPad *StrEosPadTermEmpty_StrPadType
	StrTerm *StrEosPadTermEmpty_StrTermType
	StrTermAndPad *StrEosPadTermEmpty_StrTermAndPadType
	StrTermInclude *StrEosPadTermEmpty_StrTermIncludeType
	_io *kaitai.Stream
	_root *StrEosPadTermEmpty
	_parent kaitai.Struct
	_raw_StrPad []byte
	_raw_StrTerm []byte
	_raw_StrTermAndPad []byte
	_raw_StrTermInclude []byte
}
func NewStrEosPadTermEmpty() *StrEosPadTermEmpty {
	return &StrEosPadTermEmpty{
	}
}

func (this StrEosPadTermEmpty) IO_() *kaitai.Stream {
	return this._io
}

func (this *StrEosPadTermEmpty) Read(io *kaitai.Stream, parent kaitai.Struct, root *StrEosPadTermEmpty) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(20))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this._raw_StrPad = tmp1
	_io__raw_StrPad := kaitai.NewStream(bytes.NewReader(this._raw_StrPad))
	tmp2 := NewStrEosPadTermEmpty_StrPadType()
	err = tmp2.Read(_io__raw_StrPad, this, this._root)
	if err != nil {
		return err
	}
	this.StrPad = tmp2
	tmp3, err := this._io.ReadBytes(int(20))
	if err != nil {
		return err
	}
	tmp3 = tmp3
	this._raw_StrTerm = tmp3
	_io__raw_StrTerm := kaitai.NewStream(bytes.NewReader(this._raw_StrTerm))
	tmp4 := NewStrEosPadTermEmpty_StrTermType()
	err = tmp4.Read(_io__raw_StrTerm, this, this._root)
	if err != nil {
		return err
	}
	this.StrTerm = tmp4
	tmp5, err := this._io.ReadBytes(int(20))
	if err != nil {
		return err
	}
	tmp5 = tmp5
	this._raw_StrTermAndPad = tmp5
	_io__raw_StrTermAndPad := kaitai.NewStream(bytes.NewReader(this._raw_StrTermAndPad))
	tmp6 := NewStrEosPadTermEmpty_StrTermAndPadType()
	err = tmp6.Read(_io__raw_StrTermAndPad, this, this._root)
	if err != nil {
		return err
	}
	this.StrTermAndPad = tmp6
	tmp7, err := this._io.ReadBytes(int(20))
	if err != nil {
		return err
	}
	tmp7 = tmp7
	this._raw_StrTermInclude = tmp7
	_io__raw_StrTermInclude := kaitai.NewStream(bytes.NewReader(this._raw_StrTermInclude))
	tmp8 := NewStrEosPadTermEmpty_StrTermIncludeType()
	err = tmp8.Read(_io__raw_StrTermInclude, this, this._root)
	if err != nil {
		return err
	}
	this.StrTermInclude = tmp8
	return err
}
type StrEosPadTermEmpty_StrPadType struct {
	Value string
	_io *kaitai.Stream
	_root *StrEosPadTermEmpty
	_parent *StrEosPadTermEmpty
}
func NewStrEosPadTermEmpty_StrPadType() *StrEosPadTermEmpty_StrPadType {
	return &StrEosPadTermEmpty_StrPadType{
	}
}

func (this StrEosPadTermEmpty_StrPadType) IO_() *kaitai.Stream {
	return this._io
}

func (this *StrEosPadTermEmpty_StrPadType) Read(io *kaitai.Stream, parent *StrEosPadTermEmpty, root *StrEosPadTermEmpty) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp9, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp9 = kaitai.BytesStripRight(tmp9, 64)
	this.Value = string(tmp9)
	return err
}
type StrEosPadTermEmpty_StrTermAndPadType struct {
	Value string
	_io *kaitai.Stream
	_root *StrEosPadTermEmpty
	_parent *StrEosPadTermEmpty
}
func NewStrEosPadTermEmpty_StrTermAndPadType() *StrEosPadTermEmpty_StrTermAndPadType {
	return &StrEosPadTermEmpty_StrTermAndPadType{
	}
}

func (this StrEosPadTermEmpty_StrTermAndPadType) IO_() *kaitai.Stream {
	return this._io
}

func (this *StrEosPadTermEmpty_StrTermAndPadType) Read(io *kaitai.Stream, parent *StrEosPadTermEmpty, root *StrEosPadTermEmpty) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp10, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp10 = kaitai.BytesTerminate(kaitai.BytesStripRight(tmp10, 43), 64, false)
	this.Value = string(tmp10)
	return err
}
type StrEosPadTermEmpty_StrTermIncludeType struct {
	Value string
	_io *kaitai.Stream
	_root *StrEosPadTermEmpty
	_parent *StrEosPadTermEmpty
}
func NewStrEosPadTermEmpty_StrTermIncludeType() *StrEosPadTermEmpty_StrTermIncludeType {
	return &StrEosPadTermEmpty_StrTermIncludeType{
	}
}

func (this StrEosPadTermEmpty_StrTermIncludeType) IO_() *kaitai.Stream {
	return this._io
}

func (this *StrEosPadTermEmpty_StrTermIncludeType) Read(io *kaitai.Stream, parent *StrEosPadTermEmpty, root *StrEosPadTermEmpty) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp11, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp11 = kaitai.BytesTerminate(tmp11, 64, true)
	this.Value = string(tmp11)
	return err
}
type StrEosPadTermEmpty_StrTermType struct {
	Value string
	_io *kaitai.Stream
	_root *StrEosPadTermEmpty
	_parent *StrEosPadTermEmpty
}
func NewStrEosPadTermEmpty_StrTermType() *StrEosPadTermEmpty_StrTermType {
	return &StrEosPadTermEmpty_StrTermType{
	}
}

func (this StrEosPadTermEmpty_StrTermType) IO_() *kaitai.Stream {
	return this._io
}

func (this *StrEosPadTermEmpty_StrTermType) Read(io *kaitai.Stream, parent *StrEosPadTermEmpty, root *StrEosPadTermEmpty) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp12, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp12 = kaitai.BytesTerminate(tmp12, 64, false)
	this.Value = string(tmp12)
	return err
}
