// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type StrLiteralsLatin1 struct {
	LenParsed uint16
	Parsed string
	_io *kaitai.Stream
	_root *StrLiteralsLatin1
	_parent kaitai.Struct
	_f_parsedEqLiteral bool
	parsedEqLiteral bool
}
func NewStrLiteralsLatin1() *StrLiteralsLatin1 {
	return &StrLiteralsLatin1{
	}
}

func (this StrLiteralsLatin1) IO_() *kaitai.Stream {
	return this._io
}

func (this *StrLiteralsLatin1) Read(io *kaitai.Stream, parent kaitai.Struct, root *StrLiteralsLatin1) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.LenParsed = uint16(tmp1)
	tmp2, err := this._io.ReadBytes(int(this.LenParsed))
	if err != nil {
		return err
	}
	tmp2 = tmp2
	this.Parsed = string(tmp2)
	return err
}
func (this *StrLiteralsLatin1) ParsedEqLiteral() (v bool, err error) {
	if (this._f_parsedEqLiteral) {
		return this.parsedEqLiteral, nil
	}
	this._f_parsedEqLiteral = true
	this.parsedEqLiteral = bool(this.Parsed == "\243")
	return this.parsedEqLiteral, nil
}
