// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"bytes"
)

type SwitchRepeatExpr struct {
	Codes []uint8
	Body []interface{}
	_io *kaitai.Stream
	_root *SwitchRepeatExpr
	_parent kaitai.Struct
	_raw_Body [][]byte
}
func NewSwitchRepeatExpr() *SwitchRepeatExpr {
	return &SwitchRepeatExpr{
	}
}

func (this SwitchRepeatExpr) IO_() *kaitai.Stream {
	return this._io
}

func (this *SwitchRepeatExpr) Read(io *kaitai.Stream, parent kaitai.Struct, root *SwitchRepeatExpr) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0; i < int(3); i++ {
		_ = i
		tmp1, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.Codes = append(this.Codes, tmp1)
	}
	for i := 0; i < int(3); i++ {
		_ = i
		switch (this.Codes[i]) {
		case 1:
			tmp2, err := this._io.ReadBytes(int(4))
			if err != nil {
				return err
			}
			tmp2 = tmp2
			this._raw_Body = append(this._raw_Body, tmp2)
			_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body[i]))
			tmp3 := NewSwitchRepeatExpr_One()
			err = tmp3.Read(_io__raw_Body, this, this._root)
			if err != nil {
				return err
			}
			this.Body = append(this.Body, tmp3)
		case 2:
			tmp4, err := this._io.ReadBytes(int(4))
			if err != nil {
				return err
			}
			tmp4 = tmp4
			this._raw_Body = append(this._raw_Body, tmp4)
			_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body[i]))
			tmp5 := NewSwitchRepeatExpr_One()
			err = tmp5.Read(_io__raw_Body, this, this._root)
			if err != nil {
				return err
			}
			this.Body = append(this.Body, tmp5)
		case 7:
			tmp6, err := this._io.ReadBytes(int(4))
			if err != nil {
				return err
			}
			tmp6 = tmp6
			this._raw_Body = append(this._raw_Body, tmp6)
			_io__raw_Body := kaitai.NewStream(bytes.NewReader(this._raw_Body[i]))
			tmp7 := NewSwitchRepeatExpr_Two()
			err = tmp7.Read(_io__raw_Body, this, this._root)
			if err != nil {
				return err
			}
			this.Body = append(this.Body, tmp7)
		default:
			tmp8, err := this._io.ReadBytes(int(4))
			if err != nil {
				return err
			}
			tmp8 = tmp8
			this._raw_Body = append(this._raw_Body, tmp8)
		}
	}
	return err
}
type SwitchRepeatExpr_One struct {
	First []byte
	_io *kaitai.Stream
	_root *SwitchRepeatExpr
	_parent *SwitchRepeatExpr
}
func NewSwitchRepeatExpr_One() *SwitchRepeatExpr_One {
	return &SwitchRepeatExpr_One{
	}
}

func (this SwitchRepeatExpr_One) IO_() *kaitai.Stream {
	return this._io
}

func (this *SwitchRepeatExpr_One) Read(io *kaitai.Stream, parent *SwitchRepeatExpr, root *SwitchRepeatExpr) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp9, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp9 = tmp9
	this.First = tmp9
	return err
}
type SwitchRepeatExpr_Two struct {
	Second []byte
	_io *kaitai.Stream
	_root *SwitchRepeatExpr
	_parent *SwitchRepeatExpr
}
func NewSwitchRepeatExpr_Two() *SwitchRepeatExpr_Two {
	return &SwitchRepeatExpr_Two{
	}
}

func (this SwitchRepeatExpr_Two) IO_() *kaitai.Stream {
	return this._io
}

func (this *SwitchRepeatExpr_Two) Read(io *kaitai.Stream, parent *SwitchRepeatExpr, root *SwitchRepeatExpr) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp10, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp10 = tmp10
	this.Second = tmp10
	return err
}
