// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type SwitchManualStrElse struct {
	Opcodes []*SwitchManualStrElse_Opcode
	_io *kaitai.Stream
	_root *SwitchManualStrElse
	_parent kaitai.Struct
}
func NewSwitchManualStrElse() *SwitchManualStrElse {
	return &SwitchManualStrElse{
	}
}

func (this SwitchManualStrElse) IO_() *kaitai.Stream {
	return this._io
}

func (this *SwitchManualStrElse) Read(io *kaitai.Stream, parent kaitai.Struct, root *SwitchManualStrElse) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0;; i++ {
		tmp1, err := this._io.EOF()
		if err != nil {
			return err
		}
		if tmp1 {
			break
		}
		tmp2 := NewSwitchManualStrElse_Opcode()
		err = tmp2.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Opcodes = append(this.Opcodes, tmp2)
	}
	return err
}
type SwitchManualStrElse_Opcode struct {
	Code string
	Body kaitai.Struct
	_io *kaitai.Stream
	_root *SwitchManualStrElse
	_parent *SwitchManualStrElse
}
func NewSwitchManualStrElse_Opcode() *SwitchManualStrElse_Opcode {
	return &SwitchManualStrElse_Opcode{
	}
}

func (this SwitchManualStrElse_Opcode) IO_() *kaitai.Stream {
	return this._io
}

func (this *SwitchManualStrElse_Opcode) Read(io *kaitai.Stream, parent *SwitchManualStrElse, root *SwitchManualStrElse) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp3, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp3 = tmp3
	this.Code = string(tmp3)
	switch (this.Code) {
	case "I":
		tmp4 := NewSwitchManualStrElse_Opcode_Intval()
		err = tmp4.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp4
	case "S":
		tmp5 := NewSwitchManualStrElse_Opcode_Strval()
		err = tmp5.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp5
	default:
		tmp6 := NewSwitchManualStrElse_Opcode_Noneval()
		err = tmp6.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Body = tmp6
	}
	return err
}
type SwitchManualStrElse_Opcode_Intval struct {
	Value uint8
	_io *kaitai.Stream
	_root *SwitchManualStrElse
	_parent *SwitchManualStrElse_Opcode
}
func NewSwitchManualStrElse_Opcode_Intval() *SwitchManualStrElse_Opcode_Intval {
	return &SwitchManualStrElse_Opcode_Intval{
	}
}

func (this SwitchManualStrElse_Opcode_Intval) IO_() *kaitai.Stream {
	return this._io
}

func (this *SwitchManualStrElse_Opcode_Intval) Read(io *kaitai.Stream, parent *SwitchManualStrElse_Opcode, root *SwitchManualStrElse) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp7, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Value = tmp7
	return err
}
type SwitchManualStrElse_Opcode_Noneval struct {
	Filler uint32
	_io *kaitai.Stream
	_root *SwitchManualStrElse
	_parent *SwitchManualStrElse_Opcode
}
func NewSwitchManualStrElse_Opcode_Noneval() *SwitchManualStrElse_Opcode_Noneval {
	return &SwitchManualStrElse_Opcode_Noneval{
	}
}

func (this SwitchManualStrElse_Opcode_Noneval) IO_() *kaitai.Stream {
	return this._io
}

func (this *SwitchManualStrElse_Opcode_Noneval) Read(io *kaitai.Stream, parent *SwitchManualStrElse_Opcode, root *SwitchManualStrElse) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp8, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Filler = uint32(tmp8)
	return err
}
type SwitchManualStrElse_Opcode_Strval struct {
	Value string
	_io *kaitai.Stream
	_root *SwitchManualStrElse
	_parent *SwitchManualStrElse_Opcode
}
func NewSwitchManualStrElse_Opcode_Strval() *SwitchManualStrElse_Opcode_Strval {
	return &SwitchManualStrElse_Opcode_Strval{
	}
}

func (this SwitchManualStrElse_Opcode_Strval) IO_() *kaitai.Stream {
	return this._io
}

func (this *SwitchManualStrElse_Opcode_Strval) Read(io *kaitai.Stream, parent *SwitchManualStrElse_Opcode, root *SwitchManualStrElse) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp9, err := this._io.ReadBytesTerm(0, false, true, true)
	if err != nil {
		return err
	}
	this.Value = string(tmp9)
	return err
}
