// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"bytes"
)

type TermStruct3 struct {
	S1 *TermStruct3_BytesWrapper
	S2 *TermStruct3_BytesWrapper
	S3 *TermStruct3_BytesWrapper
	_io *kaitai.Stream
	_root *TermStruct3
	_parent kaitai.Struct
	_raw_S1 []byte
	_raw_S2 []byte
	_raw_S3 []byte
}
func NewTermStruct3() *TermStruct3 {
	return &TermStruct3{
	}
}

func (this TermStruct3) IO_() *kaitai.Stream {
	return this._io
}

func (this *TermStruct3) Read(io *kaitai.Stream, parent kaitai.Struct, root *TermStruct3) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytesTerm(124, false, false, true)
	if err != nil {
		return err
	}
	this._raw_S1 = tmp1
	_io__raw_S1 := kaitai.NewStream(bytes.NewReader(this._raw_S1))
	tmp2 := NewTermStruct3_BytesWrapper()
	err = tmp2.Read(_io__raw_S1, this, this._root)
	if err != nil {
		return err
	}
	this.S1 = tmp2
	tmp3, err := this._io.ReadBytesTerm(64, false, false, true)
	if err != nil {
		return err
	}
	this._raw_S2 = tmp3
	_io__raw_S2 := kaitai.NewStream(bytes.NewReader(this._raw_S2))
	tmp4 := NewTermStruct3_BytesWrapper()
	err = tmp4.Read(_io__raw_S2, this, this._root)
	if err != nil {
		return err
	}
	this.S2 = tmp4
	tmp5, err := this._io.ReadBytesTerm(64, false, true, true)
	if err != nil {
		return err
	}
	this._raw_S3 = tmp5
	_io__raw_S3 := kaitai.NewStream(bytes.NewReader(this._raw_S3))
	tmp6 := NewTermStruct3_BytesWrapper()
	err = tmp6.Read(_io__raw_S3, this, this._root)
	if err != nil {
		return err
	}
	this.S3 = tmp6
	return err
}
type TermStruct3_BytesWrapper struct {
	Value []byte
	_io *kaitai.Stream
	_root *TermStruct3
	_parent *TermStruct3
}
func NewTermStruct3_BytesWrapper() *TermStruct3_BytesWrapper {
	return &TermStruct3_BytesWrapper{
	}
}

func (this TermStruct3_BytesWrapper) IO_() *kaitai.Stream {
	return this._io
}

func (this *TermStruct3_BytesWrapper) Read(io *kaitai.Stream, parent *TermStruct3, root *TermStruct3) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp7, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp7 = tmp7
	this.Value = tmp7
	return err
}
