// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"golang.org/x/text/encoding/unicode"
)

type TermStrzUtf16V2 struct {
	S1 string
	S2 string
	S3 string
	_io *kaitai.Stream
	_root *TermStrzUtf16V2
	_parent kaitai.Struct
}
func NewTermStrzUtf16V2() *TermStrzUtf16V2 {
	return &TermStrzUtf16V2{
	}
}

func (this TermStrzUtf16V2) IO_() *kaitai.Stream {
	return this._io
}

func (this *TermStrzUtf16V2) Read(io *kaitai.Stream, parent kaitai.Struct, root *TermStrzUtf16V2) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytesTermMulti([]uint8{0, 0}, false, true, true)
	if err != nil {
		return err
	}
	tmp2, err := kaitai.BytesToStr(tmp1, unicode.UTF16(unicode.LittleEndian, unicode.IgnoreBOM).NewDecoder())
	if err != nil {
		return err
	}
	this.S1 = tmp2
	tmp3, err := this._io.ReadBytesTermMulti([]uint8{0, 0}, true, true, true)
	if err != nil {
		return err
	}
	tmp4, err := kaitai.BytesToStr(tmp3, unicode.UTF16(unicode.LittleEndian, unicode.IgnoreBOM).NewDecoder())
	if err != nil {
		return err
	}
	this.S2 = tmp4
	tmp5, err := this._io.ReadBytesTermMulti([]uint8{0, 0}, false, false, true)
	if err != nil {
		return err
	}
	tmp6, err := kaitai.BytesToStr(tmp5, unicode.UTF16(unicode.LittleEndian, unicode.IgnoreBOM).NewDecoder())
	if err != nil {
		return err
	}
	this.S3 = tmp6
	return err
}
