// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type TermBytes3 struct {
	S1 []byte
	S2 []byte
	S3 []byte
	_io *kaitai.Stream
	_root *TermBytes3
	_parent kaitai.Struct
}
func NewTermBytes3() *TermBytes3 {
	return &TermBytes3{
	}
}

func (this TermBytes3) IO_() *kaitai.Stream {
	return this._io
}

func (this *TermBytes3) Read(io *kaitai.Stream, parent kaitai.Struct, root *TermBytes3) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytesTerm(124, false, false, true)
	if err != nil {
		return err
	}
	this.S1 = tmp1
	tmp2, err := this._io.ReadBytesTerm(64, false, false, true)
	if err != nil {
		return err
	}
	this.S2 = tmp2
	tmp3, err := this._io.ReadBytesTerm(64, false, true, true)
	if err != nil {
		return err
	}
	this.S3 = tmp3
	return err
}
