// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"bytes"
	"golang.org/x/text/encoding/unicode"
)

type TermStrzUtf16V4 struct {
	S1 *TermStrzUtf16V4_S1Type
	SkipTerm1 []byte
	S2 *TermStrzUtf16V4_S2Type
	SkipTerm2 []byte
	S3 *TermStrzUtf16V4_S3Type
	_io *kaitai.Stream
	_root *TermStrzUtf16V4
	_parent kaitai.Struct
	_raw_S1 []byte
	_raw_S2 []byte
	_raw_S3 []byte
}
func NewTermStrzUtf16V4() *TermStrzUtf16V4 {
	return &TermStrzUtf16V4{
	}
}

func (this TermStrzUtf16V4) IO_() *kaitai.Stream {
	return this._io
}

func (this *TermStrzUtf16V4) Read(io *kaitai.Stream, parent kaitai.Struct, root *TermStrzUtf16V4) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(6))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this._raw_S1 = tmp1
	_io__raw_S1 := kaitai.NewStream(bytes.NewReader(this._raw_S1))
	tmp2 := NewTermStrzUtf16V4_S1Type()
	err = tmp2.Read(_io__raw_S1, this, this._root)
	if err != nil {
		return err
	}
	this.S1 = tmp2
	tmp3, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp3 = tmp3
	this.SkipTerm1 = tmp3
	tmp4, err := this._io.ReadBytes(int(6))
	if err != nil {
		return err
	}
	tmp4 = tmp4
	this._raw_S2 = tmp4
	_io__raw_S2 := kaitai.NewStream(bytes.NewReader(this._raw_S2))
	tmp5 := NewTermStrzUtf16V4_S2Type()
	err = tmp5.Read(_io__raw_S2, this, this._root)
	if err != nil {
		return err
	}
	this.S2 = tmp5
	tmp6, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp6 = tmp6
	this.SkipTerm2 = tmp6
	tmp7, err := this._io.ReadBytes(int(6))
	if err != nil {
		return err
	}
	tmp7 = tmp7
	this._raw_S3 = tmp7
	_io__raw_S3 := kaitai.NewStream(bytes.NewReader(this._raw_S3))
	tmp8 := NewTermStrzUtf16V4_S3Type()
	err = tmp8.Read(_io__raw_S3, this, this._root)
	if err != nil {
		return err
	}
	this.S3 = tmp8
	return err
}
type TermStrzUtf16V4_S1Type struct {
	Value string
	_io *kaitai.Stream
	_root *TermStrzUtf16V4
	_parent *TermStrzUtf16V4
}
func NewTermStrzUtf16V4_S1Type() *TermStrzUtf16V4_S1Type {
	return &TermStrzUtf16V4_S1Type{
	}
}

func (this TermStrzUtf16V4_S1Type) IO_() *kaitai.Stream {
	return this._io
}

func (this *TermStrzUtf16V4_S1Type) Read(io *kaitai.Stream, parent *TermStrzUtf16V4, root *TermStrzUtf16V4) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp9, err := this._io.ReadBytesTermMulti([]uint8{0, 0}, false, true, false)
	if err != nil {
		return err
	}
	tmp10, err := kaitai.BytesToStr(tmp9, unicode.UTF16(unicode.LittleEndian, unicode.IgnoreBOM).NewDecoder())
	if err != nil {
		return err
	}
	this.Value = tmp10
	return err
}
type TermStrzUtf16V4_S2Type struct {
	Value string
	_io *kaitai.Stream
	_root *TermStrzUtf16V4
	_parent *TermStrzUtf16V4
}
func NewTermStrzUtf16V4_S2Type() *TermStrzUtf16V4_S2Type {
	return &TermStrzUtf16V4_S2Type{
	}
}

func (this TermStrzUtf16V4_S2Type) IO_() *kaitai.Stream {
	return this._io
}

func (this *TermStrzUtf16V4_S2Type) Read(io *kaitai.Stream, parent *TermStrzUtf16V4, root *TermStrzUtf16V4) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp11, err := this._io.ReadBytesTermMulti([]uint8{0, 0}, false, false, false)
	if err != nil {
		return err
	}
	tmp12, err := kaitai.BytesToStr(tmp11, unicode.UTF16(unicode.LittleEndian, unicode.IgnoreBOM).NewDecoder())
	if err != nil {
		return err
	}
	this.Value = tmp12
	return err
}
type TermStrzUtf16V4_S3Type struct {
	Value string
	_io *kaitai.Stream
	_root *TermStrzUtf16V4
	_parent *TermStrzUtf16V4
}
func NewTermStrzUtf16V4_S3Type() *TermStrzUtf16V4_S3Type {
	return &TermStrzUtf16V4_S3Type{
	}
}

func (this TermStrzUtf16V4_S3Type) IO_() *kaitai.Stream {
	return this._io
}

func (this *TermStrzUtf16V4_S3Type) Read(io *kaitai.Stream, parent *TermStrzUtf16V4, root *TermStrzUtf16V4) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp13, err := this._io.ReadBytesTermMulti([]uint8{0, 0}, true, true, false)
	if err != nil {
		return err
	}
	tmp14, err := kaitai.BytesToStr(tmp13, unicode.UTF16(unicode.LittleEndian, unicode.IgnoreBOM).NewDecoder())
	if err != nil {
		return err
	}
	this.Value = tmp14
	return err
}
