// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"bytes"
)

type ValidFailEqBytes struct {
	Foo []byte
	_io *kaitai.Stream
	_root *ValidFailEqBytes
	_parent interface{}
}
func NewValidFailEqBytes() *ValidFailEqBytes {
	return &ValidFailEqBytes{
	}
}

func (this *ValidFailEqBytes) Read(io *kaitai.Stream, parent interface{}, root *ValidFailEqBytes) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.Foo = tmp1
	if !(bytes.Equal(this.Foo, []uint8{81, 65})) {
		return kaitai.NewValidationNotEqualError([]uint8{81, 65}, this.Foo, this._io, "/seq/0")
	}
	return err
}
