// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"golang.org/x/text/encoding/japanese"
	"golang.org/x/text/encoding/charmap"
)

type ValidEqStrEncodings struct {
	LenOf1 uint16
	Str1 string
	LenOf2 uint16
	Str2 string
	LenOf3 uint16
	Str3 string
	LenOf4 uint16
	Str4 string
	_io *kaitai.Stream
	_root *ValidEqStrEncodings
	_parent kaitai.Struct
}
func NewValidEqStrEncodings() *ValidEqStrEncodings {
	return &ValidEqStrEncodings{
	}
}

func (this ValidEqStrEncodings) IO_() *kaitai.Stream {
	return this._io
}

func (this *ValidEqStrEncodings) Read(io *kaitai.Stream, parent kaitai.Struct, root *ValidEqStrEncodings) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.LenOf1 = uint16(tmp1)
	tmp2, err := this._io.ReadBytes(int(this.LenOf1))
	if err != nil {
		return err
	}
	tmp2 = tmp2
	this.Str1 = string(tmp2)
	if !(this.Str1 == "Some ASCII") {
		return kaitai.NewValidationNotEqualError("Some ASCII", this.Str1, this._io, "/seq/1")
	}
	tmp3, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.LenOf2 = uint16(tmp3)
	tmp4, err := this._io.ReadBytes(int(this.LenOf2))
	if err != nil {
		return err
	}
	tmp4 = tmp4
	this.Str2 = string(tmp4)
	if !(this.Str2 == "\u3053\u3093\u306b\u3061\u306f") {
		return kaitai.NewValidationNotEqualError("\u3053\u3093\u306b\u3061\u306f", this.Str2, this._io, "/seq/3")
	}
	tmp5, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.LenOf3 = uint16(tmp5)
	tmp6, err := this._io.ReadBytes(int(this.LenOf3))
	if err != nil {
		return err
	}
	tmp6 = tmp6
	tmp7, err := kaitai.BytesToStr(tmp6, japanese.ShiftJIS.NewDecoder())
	if err != nil {
		return err
	}
	this.Str3 = tmp7
	if !(this.Str3 == "\u3053\u3093\u306b\u3061\u306f") {
		return kaitai.NewValidationNotEqualError("\u3053\u3093\u306b\u3061\u306f", this.Str3, this._io, "/seq/5")
	}
	tmp8, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.LenOf4 = uint16(tmp8)
	tmp9, err := this._io.ReadBytes(int(this.LenOf4))
	if err != nil {
		return err
	}
	tmp9 = tmp9
	tmp10, err := kaitai.BytesToStr(tmp9, charmap.CodePage437.NewDecoder())
	if err != nil {
		return err
	}
	this.Str4 = tmp10
	if !(this.Str4 == "\u2591\u2592\u2593") {
		return kaitai.NewValidationNotEqualError("\u2591\u2592\u2593", this.Str4, this._io, "/seq/7")
	}
	return err
}
