// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type ValidFailRangeStr struct {
	Foo string
	_io *kaitai.Stream
	_root *ValidFailRangeStr
	_parent kaitai.Struct
}
func NewValidFailRangeStr() *ValidFailRangeStr {
	return &ValidFailRangeStr{
	}
}

func (this ValidFailRangeStr) IO_() *kaitai.Stream {
	return this._io
}

func (this *ValidFailRangeStr) Read(io *kaitai.Stream, parent kaitai.Struct, root *ValidFailRangeStr) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.Foo = string(tmp1)
	if !(this.Foo >= "P") {
		return kaitai.NewValidationLessThanError("P", this.Foo, this._io, "/seq/0")
	}
	if !(this.Foo <= "P1") {
		return kaitai.NewValidationGreaterThanError("P1", this.Foo, this._io, "/seq/0")
	}
	return err
}
