// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type ValidFailRepeatEqInt struct {
	Foo []uint32
	_io *kaitai.Stream
	_root *ValidFailRepeatEqInt
	_parent kaitai.Struct
}
func NewValidFailRepeatEqInt() *ValidFailRepeatEqInt {
	return &ValidFailRepeatEqInt{
	}
}

func (this ValidFailRepeatEqInt) IO_() *kaitai.Stream {
	return this._io
}

func (this *ValidFailRepeatEqInt) Read(io *kaitai.Stream, parent kaitai.Struct, root *ValidFailRepeatEqInt) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0;; i++ {
		tmp1, err := this._io.EOF()
		if err != nil {
			return err
		}
		if tmp1 {
			break
		}
		tmp2, err := this._io.ReadU4be()
		if err != nil {
			return err
		}
		this.Foo = append(this.Foo, tmp2)
		if !(this.Foo[i] == 305419896) {
			return kaitai.NewValidationNotEqualError(305419896, this.Foo[i], this._io, "/seq/0")
		}
	}
	return err
}
