// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package test_formats

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type ValidNotParsedIf struct {
	NotParsed uint8
	Parsed uint8
	_io *kaitai.Stream
	_root *ValidNotParsedIf
	_parent kaitai.Struct
}
func NewValidNotParsedIf() *ValidNotParsedIf {
	return &ValidNotParsedIf{
	}
}

func (this ValidNotParsedIf) IO_() *kaitai.Stream {
	return this._io
}

func (this *ValidNotParsedIf) Read(io *kaitai.Stream, parent kaitai.Struct, root *ValidNotParsedIf) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	if (false) {
		tmp1, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.NotParsed = tmp1
		if !(this.NotParsed == 42) {
			return kaitai.NewValidationNotEqualError(42, this.NotParsed, this._io, "/seq/0")
		}
	}
	if (true) {
		tmp2, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.Parsed = tmp2
		if !(this.Parsed == 80) {
			return kaitai.NewValidationNotEqualError(80, this.Parsed, this._io, "/seq/1")
		}
	}
	return err
}
